services:
  - type: web
    name: porto-mundo
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/server/node-build.mjs"
    envVars:
      - key: NODE_VERSION
        value: 18
